### ISSUE TITLE
Add a working inventory for testing weapons

### ISSUE THREAD

**Issue by Diarandor** [solarus-games/children-of-solarus#45] opened 2017-08-16 18:25 UTC
We need a temporary inventory for now, it does not matter if its graphics are not original.
I need it to add custom weapons (bow, feather, shield,...) and test them.

**Comment by christopho** [comment] 2017-08-31 11:25
Duplicate of #42

**Closed by christopho** 2017-08-31 11:25 UTC

**Comment by Diarandor** [comment] 2017-08-31 11:30
Oops.
